### PR TITLE
use data-type attribute for selecting node

### PR DESCRIPTION
**Pull request by jkrauss82**
see https://github.com/comfyanonymous/ComfyUI/pull/2719

### CODE REVIEW

**Comment by comfyanonymous** [comment]
Was this fixed already?

**Comment by jkrauss82** [comment]
You probably refer to this? https://github.com/comfyanonymous/litegraph.js/pull/6

It says merged but the code in the most recent version looks different 🤔

I think the current version as in the repo with the `innerHTML` does not work as it will contain a `<span>` element (in downstream ComfyUI) which is not recognized successfully inside `select()`.

**Comment by comfyanonymous** [comment]
Make sure you look at the comfyui branch not the master branch on this repo: https://github.com/comfyanonymous/litegraph.js/tree/comfyui

**Comment by jkrauss82** [comment]
I think I either made a mistake when forking or PR https://github.com/comfyanonymous/litegraph.js/pull/6 was merged after I had created the fork.

I still occasionally have the bug that a node is not created after selecting it by navigating with cursor keys and using enter. It seems to occur only if options were filtered by input and when there is only one item left but I cannot consistently reproduce it.

Closing this as it is not relevant anymore.

**Pull request closed without merging**
